# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: 'mnKy23RjNL8oGLnqtg*qRGYi^N6%6@'
    salt: 'A817mvTcxZA$xbJG05UuY2T4f55HS@'

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  iphonetwit.com:
    env:
      db_password: 'AEHg47!%2ry2Ee%ubb^#DMjreo62a&'
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "BC.j0|,+0MM^:UOjHDwSMc?l;59c&I0H5QhW^^V<!6aMbEeo!fm([qJ|mhCM_Btf"
      secure_auth_key: "3f`JC{,[lUQ9v^*127pp{y<R6K;tZYa.Xeuunit^Ai^5A*HmTAs2g@<ZAnqkyAr@"
      logged_in_key: "jgD.d*K{rGTD9mr9BH@jaFO`/ziKnNVBY_$6ROu6f6;^p67O[w_R%h+RCXh660sk"
      nonce_key: "T*;<(NbYsWGs/O4?m3v}Hq(^]yOykk(&n#*zj3{3#,BF-g$0$8lxYwRK^qN(sTd@"
      auth_salt: "<A`7b;-gZv]gVY00[o?;/E&MBJIMZB?.-^8W&f[PjUx;w|>QZ`./Q?*9[tG$$N8!"
      secure_auth_salt: "W_C02#E*^#5c-(PvcNaXoFW.MX0=c2#}ebak!SEhjrnw#Y8JNcxy0uTv(:p.<z?."
      logged_in_salt: "oOgbvUr[Og6hh-i[ZM7ukGgfIe2a[!A%{VAgJDgR/d0D5L3bu7:fA@u)rlYo{K;/"
      nonce_salt: "rw?wdL&jM6@QBKv$FW&r/a/9{*=}u/-h/mcF$b:Y/C^jZ]y;<g-=uB[[?6ue^_h3"
